### ISSUE TITLE
Implement method to retrieve deployment nounce

### ISSUE THREAD

**Issue by idea404** [zksync-sdk/zksync2-js#10]
#### 📝 Description

Implement a new method like `wallet.getDeployNonce()` that returns the deployment nounce.

#### 🤔 Rationale

To get the deployment nounce for a deploy transaction now, you need to ask for the `rawNonce` for an account (the param is uint256, you need to pad the address with zeroes to the left) https://github.com/matter-labs/era-system-contracts/blob/3e954a629ad8e01616174bde2218241b360fda0a/contracts/NonceHolder.sol#L35

After you get the value it will be of form `2^128 * deploymentNonce + normalNonce`. You then need to do the floored division (`BigNumber.div(..)`).

**Comment by danijelTxFusion** [comment]
> After you get the value it will be of form 2^128 * deploymentNonce + normalNonce. You then need to do the floored division (BigNumber.div(..)).

This is already implemented in [`_splitRawNonce()`](https://github.com/matter-labs/era-system-contracts/blob/3e954a629ad8e01616174bde2218241b360fda0a/contracts/NonceHolder.sol#L171)   which is called used by  `getDeploymentNonce()`.

**Comment by danijelTxFusion** [comment]
Implented in both SDKs:

- `zksync2-js v0.2.1`: [implementation](https://github.com/zksync-sdk/zksync2-js/blob/v0.2.1/src/adapters.ts#L730), [test](https://github.com/zksync-sdk/zksync2-js/blob/v0.2.1/tests/integration/wallet.test.ts#L142)
- `zksync-web3 v0.16.0`: [implementation](https://github.com/zksync-sdk/zksync2-js/blob/v0.16.0/src/adapters.ts#L761), [test](https://github.com/zksync-sdk/zksync2-js/blob/v0.16.0/tests/integration/wallet.test.ts#L142)
